name: checks

on:
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: requirements-dev.txt
      - name: Set up and validate
        shell: pwsh
        run: .\tools\setup.ps1 -Mode Agent -PythonVersion "${{ matrix.python }}"
